# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
branches:
  only:
  - master

r_build_args: '--resave-data --compact-vignettes="both" '

r_packages:
  - covr
  - mathjaxr

after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions=list("R/ops.R" = c(50:53,104:107), "R/mult.R" = 231))'
  